import { DownOutlined } from "@ant-design/icons";
import { Layout as AntdLayout, Breadcrumb, Menu, theme } from "antd";
import { Dropdown, Space } from "antd";
import Head from "next/head";
import { useRouter } from "next/router";
import React from "react";

import styles from "./index.module.css";

const { Header, Content, Sider } = AntdLayout;

const ITEMS = [
  {
    key: "book",
    label: "图书管理",
    children: [
      {
        key: "/book",
        label: "图书列表",
      },
      {
        key: "/book/add",
        label: "图书添加",
      },
    ],
  },
  {
    key: "borrow",
    label: "借阅管理",
    children: [
      {
        key: "/borrow",
        label: "借阅列表",
      },
      {
        key: "/borrow/add",
        label: "借阅添加",
      },
    ],
  },
  {
    key: "category",
    label: "分类管理",
    children: [
      {
        key: "/category",
        label: "分类列表",
      },
      {
        key: "/category/add",
        label: "分类添加",
      },
    ],
  },
  {
    key: "user",
    label: "用户管理",
    children: [
      {
        key: "/user",
        label: "图书列表",
      },
      {
        key: "/user/add",
        label: "图书添加",
      },
    ],
  },
];

const USER_ITEMS = [
  {
    label: "用户中心",
    key: "0",
  },
  {
    label: "退出登录",
    key: "1",
  },
];
export function Layout({ children }) {
  const {
    token: { colorBgContainer, borderRadiusLG },
  } = theme.useToken();
  const router = useRouter();
  const handleMenuClick = ({ key }) => {
    router.push(key);
  };
  return (
    <>
      <Head>
        <title>图书管理系统</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <AntdLayout>
        <Header className={styles.header}>
          <div className={styles.title}>图书管理系统</div>
          <span>
            <Dropdown menu={{ items: USER_ITEMS }}>
              <a onClick={(e) => e.preventDefault()}>
                <Space>
                  用户名
                  <DownOutlined />
                </Space>
              </a>
            </Dropdown>
          </span>
        </Header>
        <AntdLayout>
          <Sider width={200} style={{ background: colorBgContainer }}>
            <Menu
              mode="inline"
              defaultSelectedKeys={["/book"]}
              defaultOpenKeys={["book"]}
              style={{ height: "100%", borderRight: 0 }}
              items={ITEMS}
              onClick={handleMenuClick}
            />
          </Sider>
          <AntdLayout style={{ padding: "0 24px 24px" }}>
            <Breadcrumb style={{ margin: "16px 0" }}>
              <Breadcrumb.Item>Home</Breadcrumb.Item>
              <Breadcrumb.Item>List</Breadcrumb.Item>
              <Breadcrumb.Item>App</Breadcrumb.Item>
            </Breadcrumb>
            <Content
              style={{
                padding: 24,
                margin: 0,
                minHeight: 280,
                background: colorBgContainer,
                borderRadius: borderRadiusLG,
              }}
            >
              {children}
            </Content>
          </AntdLayout>
        </AntdLayout>
      </AntdLayout>
    </>
  );
}
